### ISSUE TITLE
Websockets?

### ISSUE THREAD

**Issue by jeroenvisser101** [ericmj/mint#106]
Is support for websockets already planned? It seems like the API would be quite similar to how Mint handles HTTP1/2, and it would be a nice alternative to WebSockex/gun.

**Comment by whatyouhide** [comment]
@jeroenvisser101 Websockets support is not planned yet and is not something we have discussed so far.

**Comment by ryanwinchester** [comment]
This would be incredible. I can help if I am able.

**Comment by ericmj** [comment]
As @whatyouhide said it has not been discussed yet. If you are interested in working on this please send a proposal for an API (function specs are enough) and an example on how the API should be used. Then we can discuss directly around that proposal.

**Comment by jeroenvisser101** [comment]
I think we could take a similar approach as gun where we tell Mint to negotiate upgrading an existing Mint.HTTP1 conn to Websocket protocol (either through Mint.Negotiate or Mint.Websocket). After that I think `Mint.Websocket` would use `stream/2` like others but with `{:frame, type, data}` as responses. It would also have an additional `send_frame/2` or `send/2` (to allow for sending multiple frames, like gun) to allow for sending.

**Comment by ericmj** [comment]
I would like to avoid coupling websockets to the `Mint.HTTP1` and `Mint.HTTP2` connections. On the other hand it's hard to avoid the coupling while still supporting websockets over HTTP/2 [1] because all data have to wrapped in HTTP/2 DATA frames. With a single HTTP/2 connection we should be able to have multiple websocket connections open and still be able to send normal HTTP requests on the connection.

Until we figure out this API I think we can start with simpler API that is not coupled to the connections:

```elixir
defmodule Mint.WebSocket do
  # builds request headers for upgrading a HTTP/1.1 connection or HTTP/2 stream
  @spec build_request_headers(...) :: headers()
  # status and headers from the response, sets up the websocket state and verifies server response
  @spec new(status(), headers()) :: {:ok, t()} | {:error, ...}
  # decodes data from HTTP connection to websocket frames
  @spec decode(t(), binary()) :: {t(), [frame()]}
  # encodes frames to send over HTTP connection
  @spec encode(t(), frame()) :: {t(), binary()}
end
```

The `WebSocket` module would be used like this:

```elixir
{:ok, conn} = Mint.HTTP.connect(:http, "httpbin.org", 80)
headers = Mint.WebSocket.build_request_headers(...)
{:ok, conn, ref} = Mint.HTTP.request(conn, "GET", "/", headers, nil)

message = receive(do: (message -> message))
{:ok, conn, [{:status, ^ref, status}, {:headers, ^ref, headers}, {:done, ^ref}]} =
  Mint.HTTP.stream(conn, message)
{:ok, websocket} = Mint.WebSocket.new(status, headers)

{websocket, data} = Mint.WebSocket.encode(websocket, {:text, "hello world"})
{:ok, conn} = Mint.WebSocket.stream_request_body(conn, ref, websocket)

message = receive(do: (message -> message))
{:ok, conn, [{:data, ^ref, data}]} = Mint.HTTP.stream(conn, message)
{websocket, [{:text, "hello back"}]} = Mint.WebSocket.decode(websocket, data)
```

For HTTP/2 this should work out of the box. For HTTP/1 we need to change the internals slightly so that we can receive the response while still being able to send the request body and that we don't close the request after receiving `{:done, ref}`.

Another alternative for HTTP/1 is to drop the `%Mint.HTTP1{}` connection after receiving the HTTP response and work with `{:tcp, socket, data}` messages directly, we can do that because unlike with HTTP/2 we don't need to do any additional framing. The downside of this is that users would need to use two separate APIs for HTTP/1 and HTTP/2.

[1] https://tools.ietf.org/html/draft-ietf-httpbis-h2-websockets-00

**Comment by ericmj** [comment]
This could be built as a separate library to test the API.

**Comment by the-mikedavis** [comment]
:wave: hey y'all

we've got a working implementation here as a separate library: https://github.com/NFIBrokerage/mint_web_socket

although the API is slightly different than above:

```elixir
defmodule Mint.WebSocket do
  # perform the upgrade request using Mint.HTTP.request/5
  @spec upgrade(
          Mint.HTTP.t(),
          path :: Mint.Types.path(),
          Mint.Types.headers(),
          opts :: Keyword.t()
        ) ::
          {:ok, Mint.HTTP.t(), Mint.Types.request_ref()}
          | {:error, Mint.HTTP.t(), Mint.WebSocket.error()}

  # create a new websocket data structure
  @spec new(
          Mint.HTTP.t(),
          Mint.Types.request_ref(),
          Mint.Types.status(),
          response_headers :: Mint.Types.headers()
        ) ::
          {:ok, Mint.HTTP.t(), Mint.WebSocket.t()}
          | {:error, Mint.HTTP.t(), Mint.WebSocket.error()}

  # encode a frame
  # can be sent with Mint.HTTP.stream_request_body/3
  @spec encode(Mint.WebSocket.t(), Mint.WebSocket.frame()) ::
          {:ok, Mint.WebSocket.t(), binary()} | {:error, Mint.WebSocket.t(), term()}

  # decode a data packet into WebSocket frames
  # works on data packets returned by Mint.HTTP.stream/2
  @spec decode(Mint.WebSocket.t(), binary()) ::
          {:ok, Mint.WebSocket.t(), [Mint.WebSocket.frame() | {:error, term()}]}
          | {:error, Mint.WebSocket.t(), term()}
end
```

because of how different the HTTP/1 and HTTP/2 bootstraps are.
