### ISSUE TITLE
Use selective receive instead of receiving whatever the first message in process memory block in the document

### ISSUE THREAD

**Issue by blisscs** [ericmj/mint#173]
Hi, 

As per mint's document, the receive block that receives mint's messages are written as below

```elixir
receive do
  message ->
      case Mint.HTTP.stream(conn, message) do
        :unknown -> handle_normal_message(message)
        {:ok, conn, responses} -> handle_responses(conn, responses)
      end
end 
``` 

For the above `receive block`, I think we should use `selective receive block` in the library document instead of the one shown above. Since by nature of interprocess communication in BEAM languages, any processes can send messages to any other processes. That means, at any time, there might be other messages in front of the process memory block queue, when we are trying to process mint receive block.

By implementing as suggested by mint's document, we might be fetching some messages that should not be fetched out at the time of executing this mint's `receive block`.

I think we need to use a more specific pattern to match and fetch only mint's messages out to be handled in all of mint's document.

**This suggestion is so that, developers can use (or just copied) it without considering that there are might be some messages in the queue before mint's messages**

I have created a [post](https://elixirforum.com/t/comment-on-mints-receive-block/22886) on the elixirforum to ask about this, to get some comments also.

I have got a reply from [@jwlander](https://elixirforum.com/u/jwarlander/summary), that we could use pattern as below to do what is wanted. 

```elixir
receive do
  {tag, _, _} = msg when tag in [:tcp, :ssl, :tcp_error, :ssl_error] ->
    process_mint_message(msg)
  {tag, _} = msg when tag in [:tcp_closed, :ssl_closed] ->
    process_mint_message(msg)
end
```

By doing the selective case as above we are not fetching out any non-mint's messages from the process memory block. Which I think, this should be default case written in all mint document. 

I realize that there are some drawbacks in term of performance when doing selective receive like above. As also given by @jwlander in [link](https://elixirforum.com/t/comment-on-mints-receive-block/22886).

So, I would like to ask about putting selective receive block in the document, instead of the ones shown now. If it's acceptable, I could send a pull request for it. 

Best
Dev.

**Comment by ericmj** [comment]
In this case we think it's better to keep it simple in the docs by receiving any message and pass off non mint messages to the `handle_normal_message/1` function. Neither is more correct than the other because both are viable approaches depending on your application, for example when you are using `GenServer.handle_info` your `receive` will effectively work like a match all.

Also note that your receive block can still match messages from other sockets so you still need to handle the `:unknown` return value from mint.

**Comment by blisscs** [comment]
Do you mean that even I use the code as below, it's still be possible to get `:unknown`  
```elixir
receive do
  {tag, _, _} = msg when tag in [:tcp, :ssl, :tcp_error, :ssl_error] ->
    process_mint_message(conn, msg)
  {tag, _} = msg when tag in [:tcp_closed, :ssl_closed] ->
    process_mint_message(conn, msg)
end

def process_mint_message(conn, msg) do
   case Mint.HTTP.stream(conn, message) do
     :unknown -> dosomething() # Do I still need to handle for non mint message here also?
     {:ok, conn, responses} -> handle_mint_msg(response) 
   end
end
```

**Comment by whatyouhide** [comment]
@blisscs yes, with the code you showed it's still possible to get `:unknown` because you're matching on TCP/SSL messages coming from **all** sockets whose controlling process is the one that executes that code. If you open two Mint connections, you'll receive `:tcp`/`:ssl` messages for both and each one will return `:unknown` for messages destined to the other one.

I think it's really important to stress what @ericmj said about things like `GenServer.handle_info/2`, which essentially does the same and skips selective receive by forcing you to process all messages.

**Comment by blisscs** [comment]
Thank you @whatyouhide  and @ericmj for added information. 

I think to be safe if I don't want to fetch non-mint messages and I also would not want to handle `:unknown` cases I should always spawn a new process to create a new mint request.

I think, there will be only one case that the above scenario would not be true, that is if one process, who is sending a mint request, is also a group_leader of another process that is also sending that is sending another mint request. Then process who is the group_leader will also receive the message that should destine to another process also. I think this would be the only case that my scenario above would not be true.

**Comment by ericmj** [comment]
We could expose the socket so that you can match on that as well. But I think the main question is why do you only want to match on messages for mint? In my experience I very rarely use selective receive where I can only match specific messages and instead I try to use higher abstractions with the OTP processes.

**Comment by whatyouhide** [comment]
@blisscs I don't think that's the case. I think most processes that will use a Mint connection will consume all messages anyways because there's a high chance that they'll be GenServers (where `handle_info/2` consumes all messages anyways).

**Comment by ericmj** [comment]
If you can only handle mint messages it might be better to be able to switch to passive mode: https://github.com/ericmj/mint/issues/170.

**Comment by blisscs** [comment]
@ericmj I was just little curious about the ideas behind not using selective receive in mint. 
I have no use cases yet, I was just poking around and I think that I would handle it in different ways. 

@whatyouhide I agree with you that `most processes that will use a Mint connection will consume all messages anyways because there's a high chance that they'll be GenServers (where handle_info/2 consumes all messages anyways).`

@ericmj thank you for introducing the passive mode. Will checked out.

**Comment by whatyouhide** [comment]
>  I was just little curious about the ideas behind not using selective receive in mint.

The reason is that we cannot do selective receive in Mint. The way that Erlang works is that when a process receives a message there's no way for a third-party (like a library) to intercept and modify that message. This means that users can only receive raw `:tcp`/`:ssl` messages. We don't want Mint users to have to care about the shape of those messages or about where's the socket or about having to take care of `:tcp_closed`/`:ssl_closed` and so on. Hope that clarifies things. I'm going to close this issue due to the fact that right now we have no real use case and #170 might incidentally fix this anyways. Thanks @blisscs! 💟
