### ISSUE TITLE
How to handle redirects

### ISSUE THREAD

**Issue by at88mph** [ericmj/mint#185]
I'm writing a system that will stream huge files and cutout ranges of bytes.  I have the streaming method from the examples:

```elixir
  def read_huge_file(url) do
    uri = URI.parse(url)
    {:ok, conn} = Mint.HTTP.connect(String.to_atom(uri.scheme), uri.host, uri.port)
    {:ok, conn, _request_ref} = Mint.HTTP.request(conn, "GET", uri.path || "/", [])

    receive_and_stream(conn)
  end
```

```elixir
  defp handle(conn, ...) do
    # Do cutout stuff or other things with other handle method matches...
  end 
```

```elixir
  defp handle(
         conn,
         [
           {:status, _, status},
           {:headers, _, headers},
           {:done, _}
         ]
       )
       when status > 300 and status < 400 do
    location_header = headers |> Enum.find(&match?({"location", _}, &1))

    IO.puts("Checking for redirect...")

    # Do I need to close it when :done is set?
    {:ok, _} = Mint.HTTP.close(conn)

    if is_nil(location_header) do
      raise "No redirect location found."
    else
      location = location_header |> elem(1)
      IO.puts("Moving on to #{location}")
      location |> read_huge_file()
    end
  end
```

```elixir
  defp receive_and_stream(conn) do
    receive do
      message ->
        case Mint.HTTP.stream(conn, message) do
          :unknown -> handle_unknown(conn, message)
          {:ok, conn, response} -> 
              handle(conn, response, do_not_scale_image_data, remove_checksums)
              receive_and_stream(conn)
        end
    end
  end
```

The problem is that when the redirect `handle` method matches, it opens another connection and then the existing process receives an :unknown.  Do I need to handle it differently?  Should I somehow kill the existing process when a new connection is made?

Thanks!

**Comment by whatyouhide** [comment]
Hey @at88mph, thanks for the report! I'm a bit confused about your questions. I'm not exactly sure what you're trying to do.

> the existing process receives an :unknown. Do I need to handle it differently?

If you open a new Mint connection for the redirected host and then get a message, you should run it through both the old connections and the new connection because you don't know which connection it's for. One of the two connections will return `:unknown` and that's how you know that message is not meant for that connection.

> Do I need to close it when :done is set?

I don't know if you need to close it because I don't know how you plan to use the old connection. Anyways, yes, a request is done once either `{:done, ref}` or `{:error, ref, reason}` is returned for that request.

Let me know if this answers your questions, otherwise I think I'll need to understand more about what you're trying to do :).

**Comment by at88mph** [comment]
Hi @whatyouhide,

Thanks for the reply!  I'm used to an HTTP Connection in Java, for example, where the redirects are followed automatically if it's configured.  If it's not configured, I simply pull the `Location` header out of the HTTP Response and issue another connection, and the old connection is completely forgotten about.

In this case, I think I still need to deal with every open connection, is that true?  In that case, when I receive the `:unknown` match, I can ignore it, I think.  Does that clarify?

**Comment by whatyouhide** [comment]
> I think I still need to deal with every open connection, is that true?

Yes. Mint is low level and connections are managed explicitly, so we won't follow redirects (because it would involve opening a new connection and we don't want to do that implicitly) and you'll have to deal with all the connections yourself. 

> In that case, when I receive the :unknown match, I can ignore it, I think.

If you close "old" connections and open a new connection to the `Location` host, and on that connection you get `:unknown`, I guess that yes, you can ignore them. I don't think there would be problems.

In any case, I don't think this is specifically an issue. I opened #190 to see if we want to add a guide on how to handle redirects, but I'm going to close this. Thank you @at88mph! 💟

**Comment by at88mph** [comment]
Many thanks, @whatyouhide!  That clarifies things for me.  Thank you for opening #190, too.
