### ISSUE TITLE
scheme and method should be both "atom"

### ISSUE THREAD

**Issue by ggerico** [ericmj/mint#197]
While in the function `Http.connect` the scheme is **an atom** of value `:http` or `:https`, the method in the function `Http.request` is **a string**. Why not use atoms in both cases ? 
Is there any special reason ? 

I got 400 errors for the last hour because I spelled the method "get" instead of "GET" ~

**Comment by ericmj** [comment]
The scheme is an atom because we only support two values `:http | :https`. The method is a string because we support any string. The specification allows lowercase methods so unfortunately we cannot validate or automatically upcase.

**Comment by whatyouhide** [comment]
I don't think there's anything we can do here. We could support atom methods and convert them to uppercase strings, but I think that would be confusing in its own way. Thanks for the report @ggerico! 💟

**Comment by dsincl12** [comment]
Hi everyone,

I just stumbled upon Eric's YouTube talk about Mint and looked around and got a bit baffled why the request methods are magic strings. I found this issue and don't really understand why it's just closed? Seems like it would be a really good idea to have these to avoid mistakes for the simple reason above. Anyway, just curious since this is normally bad practice.

**Comment by ericmj** [comment]
The strings are not magic, mint just sends them without interpreting them in any way. We need to allow any strings to not be limited to a set of pre defined methods. If you want to restrict the allowed methods then I think it's best for you to add that on top of mint.

**Comment by dsincl12** [comment]
Well a magic string is more often referring to a string value that has an impact on behaviour  (which this does) and is a known source for bugs (as seen in the comment at the top). There is a predefined set of request methods in the specs so I don't understand why you would allow anyone to send anything there, "ASDF" doesn't make any sense for example. Anyway, just wondering, I don't want to argue.

**Comment by ericmj** [comment]
The specifications only define a set of common methods. You are certainly allowed to define and use your own methods and that happens in the wild.

As I see it the method string is not any more magic than the header and body strings, if you change them you will also introduce bugs. From what I can tell when reading the spec again, it does not say that the request methods are any more special than any other free form strings in HTTP.

**Comment by whatyouhide** [comment]
@dsincl12 the HTTP specs define a few **predefined** request methods which have a well-defined meaning (such as `GET`, `POST`, and so on), but it doesn't limit methods to these predefined one so that adding new methods won't break HTTP compatibility. For example, [WebDAV](https://en.m.wikipedia.org/wiki/WebDAV) specifies new methods. Mint is too low level to enforce methods and Mint adheres to the HTTP spec which allows any method. If you want something stricter, I agree that the right way to go is to build that on top of Mint.
