### ISSUE TITLE
Add support for string scheme in HTTP.connect?

### ISSUE THREAD

**Issue by ryanwinchester** [ericmj/mint#198]
I think allowing the string versions would at the very least get rid of a minor inconvenience.

```elixir
uri = URI.parse("https://example.com")
scheme = String.to_existing_atom(uri.scheme)
{:ok, conn} = HTTP.connect(scheme, uri.host, uri.port)
{:ok, conn, ref} = HTTP.request(conn, "GET", uri.path, [])
```

**Comment by whatyouhide** [comment]
Hey @ryanwinchester, thanks for the issue. We're using an atom because the scheme can only be `:http` or `:https`. I think allowing a string as well goes against the philosophy of Mint, which is to be a low-level client that behaves correctly and supports everything supported by HTTP/1 and HTTP/2, but without adding conveniences on top (which would be the responsibility of the user or of libraries built on top of Mint).

Hope that makes sense. Thanks a lot in any case! 💟
