### ISSUE TITLE
Mint sometimes give :nxdomain error

### ISSUE THREAD

**Issue by blisscs** [ericmj/mint#216]
Hi, 

we have been using mint version 0.2.1 for a while in our project.
we sometimes get {:badmatch, {:error, %Mint.TransportError{reason: :nxdomain}}} errors. Could you recommend how to find the root cause of this? 

This sometimes happens when we use mint during the test, in only some of the tests not all of them.

To give more information about this error. The workflow that I am using mint is like below -

Mint requests are executed inside a GenServer processes.

We spawn a genserver for every mint's request, then that genserver execute the request, then genserver returns result to the caller. Then the caller kills the mint process.

**Comment by whatyouhide** [comment]
Hey @blisscs, `:nxdomain` means that Mint wasn't able to resolve the domain through DNS. Mint is just calling `:gen_tcp.connect/4` or `:ssl.connect/4` under the hood and that's almost surely where this is coming from. It's likely that the problem lies elsewhere and not in Mint. For these reasons, I will close this issue but if you manage to provide us with a reproducible case where you can pin point this to Mint, we'll be more than happy to take a look 😊 💟
