### ISSUE TITLE
Stricter error contract

### ISSUE THREAD

**Issue by ericmj** [ericmj/mint#43]
The general error contract in xhttp is currently `{:error, term()}` which is pretty vague.

Looking through the code I think we can make this stricter to `{:error, :inet.posix() | atom()}` which is equivalent to `{:error, atom()}`.

**Comment by whatyouhide** [comment]
Should we look into having a `XHTTP.Error` exception that can be raised or converted to a human error with `Exception.message/1`?

**Comment by ericmj** [comment]
We can do that as long as we can get the underlying error atom from the exception.

**Comment by whatyouhide** [comment]
Working on this right now.

**Comment by wojtekmach** [comment]
Are SSL errors possible here? If so, they can be e.g.: `{:error, {:tls_alert, ...}}`

**Comment by whatyouhide** [comment]
Yes @wojtekmach, all kind of errors are possible: TCP/SSL errors plus our own defined errors. For example, HTTP/2 uses a bunch of errors like `:max_concurrent_streams_reached`. The plan is to have a `Mint.Error` exception struct with a `:reason` key that keeps the reason intact if you want to access it. `Mint.Error` will provide `message/1` so that we can transform every error reason in a human-friendly message to be used in exception or logs. Wdyt?

**Comment by wojtekmach** [comment]
Yup, sounds good! I just wanted to point that if `:reason` is in this case broader than `atom()`.

**Comment by whatyouhide** [comment]
@wojtekmach yep, the reason is definitely not `atom/0` but `term/0` :).

**Comment by ericmj** [comment]
Follow up in https://github.com/ericmj/mint/issues/131.

**Comment by wojtekmach** [comment]
@whatyouhide have you seen OTP 21.3? It introduced a [`:ssl.error_alert()` type](http://erlang.org/doc/man/ssl.html#type-error_alert), so the reason could be, as far as I can tell, the following:

```elixir
reason ::
  :closed |
  :timeout |
  :bad_alpn_protocol |
  :protocol_not_negotiated |
  :inet.posix() |
  :ssl.error_alert()
```

Btw, since ssl errors are always a tuple perhaps there's less of a need of `formatter_module` on the exception, e.g. use `:ssl.format_error` if it's an `{:tls_alert, ...}` tuple, your own message for things like `:closed`, `:timeout` etc, otherwise try `:inet.format_error`.

The downside of depending on `:ssl.error_alert()` type is people would get a Dialyzer warning on earlier OTP versions. That might be deal breaker, curious what you think.

Btw, out of curiosity what are the reasons to have reason opaque? Because if it needs to stay opaque then this conversation is somewhat moot :)

**Comment by ericmj** [comment]
It is opaque because we need to be able to add new errors in the future without breaking backwards compatibility.

We might do `@type reason :: :closed | ... | term()` to work around that or just document it.
