### ISSUE TITLE
Add caching support

### ISSUE THREAD

**Issue by pezra** [ericmj/mint#90]
This library looks like a great opportunity to bring HTTP caching support to the BEAM. Because caching requires low level access to the request immediately before it is put on the wire it is hard to add to higher level libraries after the fact. 

Adding a cache check and short circuit to `request/5` and cache upsert in `stream/2` would be awesome. @ericmj, is that something you'd be interested in having in this library? If so, i might be to do/help with the implementation.

**Comment by ericmj** [comment]
Are you talking about conditional HTTP requests or fully cached requests, or both?

My immediate thinking is that it would be hard to make it fit the connection API since responses are returned from a different function than where you made the request. Can you give an example of what the API would look like?

**Comment by pezra** [comment]
I hope both. I think we could maintain the same interface. 

## cache hit scenario

`Mint.HTTP.request/5` would check the cache for a matching entry. If a fresh matching entry was found it send a "cache hit" message to `self` with a reference to the matching entry in the cache. `Mint.HTTP.stream/2` have a "cache hit" handling clause that would fetch the response from the cache and return it as if the request has actually been made.

## conditional request

`Mint.HTTP.request/5` would check the cache for a matching entry. If a stale matching entry was found it would add the appropriate conditional request headers and make the request. If a "not modified" response was received `Mint.HTTP.stream/2` fetch the previous response from the cache and return it.

## connecting

We could define an HTTP cache behavior (or maybe protocol?) and extend `connect/2` to accept an optional cache argument. That cache would be added to the connection to make it available to `request` and `stream`.

**Comment by ericmj** [comment]
> `Mint.HTTP.stream/2` have a "cache hit" handling clause that would fetch the response from the cache and return it as if the request has actually been made.

This would not be possible because `stream/2` is passed tcp messages. In the case of a cache hit we would have no messages and `stream/2` would not be called.

**Comment by pezra** [comment]
> stream/2 is passed tcp messages

I don't follow why a `def stream(conn, {:cache_hit, cache_entry_ref})` clause would be infeasible. There are already clauses that don't match on tcp messages (eg, https://github.com/ericmj/mint/blob/master/lib/mint/http1.ex#L233 and https://github.com/ericmj/mint/blob/master/lib/mint/http1.ex#L255)

**Comment by ericmj** [comment]
Thanks for finding https://github.com/ericmj/mint/blob/master/lib/mint/http1.ex#L233, that's a bug, it should indeed match on socket messages. https://github.com/ericmj/mint/blob/master/lib/mint/http1.ex#L233 is explicitly about ignoring any other messages than socket messages.

It feels a bit hacky to use messages to add request caching. It also makes it harder to explain what messages should expect in their process since it's no longer socket messages and we have another message type to document. I think a separate module that is not coupled to the connection API would be better:

```elixir
defmodule Cache do
  @spec fetch(hostname(), port(), method(), path(), headers()) :: {:ok, [response()]} | :error
end
```

This also means we don't have to localize the cache to a specific connection and can instead have it global for all connections. What do you think?

**Comment by pezra** [comment]
Adding another message tag feels pretty elegant to me. Describing 3 vs 2 tags is a small thing. I do think the docs should be clearer about what messages to expect and handle, regardless of this issue.

A separate module is not as tightly integrated as I'd prefer but given how low level this library is it is workable. Would such a module be welcome in this library?

I don't think the cache would necessarily be local to the connection either way. It'd be nice to have a global "public" cache and then multiple "private" caches. A connection would be started with a private cache that could potential be shared across multiple connections.

**Comment by ericmj** [comment]
I am not sure if such a cache fits in Mint, would need to check with the other maintainers. It is quite separate from Mint, the proposed API only shares the response type, so I think it could work as a separate library just as well.

If you decide to build it as a separate library I would love to help out and give my feedback.

**Comment by whatyouhide** [comment]
I think that with time we have learned that Mint is a simple HTTP wrapper around TCP/SSL connections. Its only job is to handle the HTTP **protocol** and caching can be considered an application concern. For this reason, I'm inclined to close this issue. Wdyt @ericmj?

**Comment by ericmj** [comment]
Yes, agreed. If anyone would like to build a library for this we would be happy to provide support.
